# Generated by Django 5.1.3 on 2024-11-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositWithdraw",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("bank_code", models.CharField(max_length=10)),
                ("balance", models.IntegerField()),
                ("account_type", models.CharField(max_length=20)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deposit", models.IntegerField()),
                ("withdraw", models.IntegerField()),
                ("balance", models.IntegerField()),
                ("details", models.CharField(max_length=50)),
                ("dw_type", models.CharField(choices=[("입금", "입금"), ("출금", "출금")], max_length=10)),
                (
                    "ts_type",
                    models.CharField(
                        choices=[
                            ("현금", "현금"),
                            ("계좌이체", "계좌이체"),
                            ("자동이체", "자동이체"),
                            ("카드결제", "카드결제"),
                        ],
                        max_length=10,
                    ),
                ),
                ("td_date", models.DateField()),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bank.accounts")),
            ],
        ),
    ]
