# Generated by Django 5.1.3 on 2024-12-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="td_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
