# Generated by Django 5.1.3 on 2024-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_alter_transactionhistory_td_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="balance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
