# Generated by Django 5.1.3 on 2024-12-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="users",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
