# Generated by Django 5.1.3 on 2024-12-01 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
