# Generated by Django 5.1.3 on 2024-12-03 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("about", models.CharField(max_length=50, verbose_name="About")),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("period_start", models.DateField(verbose_name="Start Date")),
                ("period_end", models.DateField(verbose_name="End Date")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("result_image", models.ImageField(null=True, upload_to="analysis/image", verbose_name="Result Image")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
