# Generated by Django 5.1.3 on 2024-12-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("bank", "0003_alter_transactionhistory_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="account",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="bank.accounts"),
            preserve_default=False,
        ),
    ]
